version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14.x
  pre_build:
    commands:
      - npm install -g yarn
      - yarn
  build:
    commands:
      - yarn build

artifacts:
  files:
    - '**/*'
  base-directory: build

cache:
  paths:
    - '/node_modules/**/*'