version: 0.2

phases:
  pre_build:
    commands:
      - npm install -g yarn
      - yarn
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 sync build s3://tle-dev-asadahyuma-frontend

artifacts:
  files:
    - '**/**'
  base-directory: build

cache:
  paths:
    - 'usr/local/bin/yarn/**/*'